AWSTemplateFormatVersion: 2010-09-09
Description: Simple EC2 instance
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html

Resources:
  ExInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0b5eea76982371e91
      InstanceType: t2.micro
